version: '2.1'
services:
  frontend:
    build: .
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/ethereum
  testchain:
    image: node:16
    ports:
      - '8545:8545'
    command: bash -c "npm i -g ganache-cli && ganache-cli -h 0.0.0.0"
  ethereum:
    build: ./ethereum/.
    depends_on:
      - testchain
